# Generated by Django 5.2.7 on 2026-07-11 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "title_hanja",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="한자 제목"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="출판사"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="발행 연도"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="소개")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="collections/",
                        verbose_name="표지 이미지",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
            ],
            options={
                "verbose_name": "시집",
                "verbose_name_plural": "시집 목록",
                "ordering": ["order", "year"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                (
                    "month",
                    models.IntegerField(blank=True, null=True, verbose_name="월"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="사건")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
            ],
            options={
                "verbose_name": "연보 이벤트",
                "verbose_name_plural": "연보",
                "ordering": ["year", "month"],
            },
        ),
        migrations.CreateModel(
            name="Poem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("body", models.TextField(verbose_name="본문")),
                (
                    "year",
                    models.IntegerField(blank=True, null=True, verbose_name="연도"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="추천(홈 노출)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="해설/출처 메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poems",
                        to="archive.collection",
                        verbose_name="수록 시집",
                    ),
                ),
            ],
            options={
                "verbose_name": "시",
                "verbose_name_plural": "시 목록",
                "ordering": ["-is_featured", "year", "title"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MANUSCRIPT", "육필"),
                            ("ARTIFACT", "유품"),
                            ("DOCUMENT", "문헌"),
                            ("PHOTO", "사진"),
                        ],
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "date_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="연대(자유 표기)"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="연도(정렬용)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="archive_items/",
                        verbose_name="이미지",
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(blank=True, verbose_name="판독/AI 추출 텍스트"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="네이버 블로그 아카이브",
                        max_length=200,
                        verbose_name="출처",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_poem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_items",
                        to="archive.poem",
                        verbose_name="관련 시",
                    ),
                ),
            ],
            options={
                "verbose_name": "아카이브 자료",
                "verbose_name_plural": "아카이브 자료 목록",
                "ordering": ["-year", "title"],
            },
        ),
    ]
